from typing import Protocol

from app.domain.knowledge.entity import Document, DocumentChunk, KnowledgeBase, SearchHit


class RagRepository(Protocol):
    async def create_knowledge_base(self, kb: KnowledgeBase) -> KnowledgeBase: ...

    async def get_knowledge_base(self, *, kb_id: str, workspace_id: str) -> KnowledgeBase | None: ...

    async def list_knowledge_bases(self, *, workspace_id: str, limit: int, offset: int) -> list[KnowledgeBase]: ...

    async def delete_knowledge_base(self, *, kb_id: str, workspace_id: str) -> bool: ...

    async def create_document(self, document: Document) -> Document: ...

    async def get_document(self, *, document_id: str, workspace_id: str) -> Document | None: ...

    async def update_document_status(
        self,
        *,
        document_id: str,
        workspace_id: str,
        status: str,
        chunk_count: int,
    ) -> None: ...

    async def add_chunks(self, chunks: list[DocumentChunk]) -> None: ...

    async def list_chunks_for_kb(self, *, knowledge_base_id: str, workspace_id: str) -> list[DocumentChunk]: ...

    async def delete_document(self, *, document_id: str, workspace_id: str) -> bool: ...
